### PR TITLE
Add @wordpress/icons package as externals

### PR DESCRIPTION
**Pull request by mattheu**
Would be good to support this package: https://github.com/WordPress/gutenberg/blob/trunk/packages/icons

### CODE REVIEW

**Comment by mattheu** [comment]
@kadamwhite Updated this branch and rebased against v1 branch - the TravisCI integration was failing against `main`

**Comment by kadamwhite** [comment]
Thanks @mattheu. Can you comment on why this should be part of the core helpers versus something that gets added on a project level? I'm a little concerned the plugins list is becoming a "kitchen sink"

**Comment by mattheu** [comment]
Oh I guess it can be added at a project level... which I have done for now. But I guess I saw this as something that should probably mirror all the packages WordPress makes available globally.

**Comment by Sephsekla** [comment]
Resolved by #217

**Pull request closed without merging**
