### PR TITLE
Support Class Properties

### LINKED ISSUE #24: Instance properties not supported out of the box
I was wondering why instance properties are not supported by the Babel preset/config.

I am used to write stateful class-based components like so:

```js
class Foo {
    state = {
        foo: 'bar',
    };
}
```

And I'm sure I'm not alone ... am I? 😁

 @kadamwhite - can we add the `@babel/plugin-proposal-class-properties` Babel plugin, please? Or do you expect it to not be used regularly?

### PR DESCRIPTION
**Pull request by tfrommen**
Fixes #24.

I added the package and included it in the Babel config, and I also updated the readme/guide mentioning the contents of this package's Babel config.

Not sure if I missed anything anywhere, but I hope not. 😅

### CODE REVIEW

**Comment by kadamwhite** [comment]
@tfrommen I'm not sure if this makes sense, but would you think it's a good idea to include a directory of JS files which should be able to be processed using this config -- and then a test script to make sure they work without failure? Or is that massive overkill :thinking:

**Comment by tfrommen** [comment]
@kadamwhite hm, I'm not sure either. I mean, what should these files include? The WordPress Babel config alone (which is based on `babel-preset-env`) includes so many different things that I don't see a straightforward way to write a _test_ JS file, or multiple, for that. 🤔

If more and more projects use this package (and the Babel config), I think that's good enough real-life testing. But I certainly understand your thinking here.

**Comment by tfrommen** [comment]
@kadamwhite do you have any thoughts on this? Do we want to merge this, and maybe follow up with some tests, however they may look?

**Comment by kadamwhite** [comment]
We can land as-is :)

**Pull request merged**
