### PR TITLE
Update Externals

### LINKED ISSUE #26: externals does not include @wordpress/block-editor
This is where InnerBlocks currently lives, and suggests our externals may be out of date with WP 5.2. Review & audit the full externals module.

### PR DESCRIPTION
**Pull request by tfrommen**
Fixes #26, and also adds all the other missing dependencies/externals.

### CODE REVIEW

**Comment by kadamwhite** [comment]
Looks like CI failed; I’ve probably defined a test that breaks when this changes. I think that’s a bad test and we should remove or adapt it. @tfrommen you mind taking a look?

**Comment by tfrommen** [comment]
Hm, I'm unsure about the value of such a test. I mean, I could easily use `.toMatchObject()` here, but not sure. Remove?

**Comment by tfrommen** [comment]
Thinking about that again, I do see value in the _effect_ of the test, but not so much having to manually update possibly multiple values in two places.

However, what if we made that a snapshot test instead? That's a super simple, straightforward, and yet effective non-manual assertion. You'd only have to run the tests locally, understand the change in the snapshot (if there is one, and have it update automatically with a single keypress if all is good.

**Comment by kadamwhite** [comment]
A snapshot could work! Otherwise we can just remove. I’m good either way

**Comment by tfrommen** [comment]
@kadamwhite I just added the adapted test including snapshot. Travis is all good now.
(And while doind so, I found another bug, in a test. Expect a follow-up PR. 😅)

**Comment by kadamwhite** [comment]
Thank you, @tfrommen !

**Pull request merged**
