### PR TITLE
Update externals for WP 6.2 and add snapshot update command

### PR DESCRIPTION
**Pull request by Sephsekla**
- Add an npm command to update Jest snapshots (`npm run update-snapshot`) without global Jest
- Update the WP external packages based on the WP 6.2 branch of the Gutenberg plugin (from 5.7)

Note that all changes are additional externals, rather than removals. One external has been removed as a Gutenberg dependency (`@wordpress/nux` https://developer.wordpress.org/block-editor/reference-guides/packages/packages-nux/), but I've left this in out of caution - it's a very niche package so it may be it's not anything to worry about, but I will need to look into whether WP still exposes it as an external in newer versions.

### CODE REVIEW

**Comment by Sephsekla** [comment]
Travis is running into issues with this but I think it may just be because our CI setup is pretty out of date - we're still running on things like Node 10 😬 .

I'm thinking we could update to a github actions based setup, which I've have really positive experiences with, any thoughts?

**Comment by Sephsekla** [comment]
Or on reflection, could integrate https://github.com/WordPress/gutenberg/blob/trunk/packages/dependency-extraction-webpack-plugin/README.md

**Review by kadamwhite — APPROVED** [review]
Thanks for this, @Sephsekla.

Once this merges, can you take on getting a point release of the 0.x branch out, and also merge `main` back into the 1.0-beta branch?

**Comment by Sephsekla** [comment]
@kadamwhite I can sort this, I think the only thing I can't do is publish the release to npm, I don't believe I have access.

**Pull request merged**
