### PR TITLE
Add plugins.errorBell() to create BellOnBundleErrorPlugin instance

### PR DESCRIPTION
**Pull request by kadamwhite**
@johnbillion @igmoweb Took a while, but I had a crack at adding this. Can you review / possibly test?

### CODE REVIEW

**Comment by johnbillion** [comment]
Tested this on the SW project and it's working as expected. IMHO we should include this in both presets so it's zero config and enabled by default.

**Comment by kadamwhite** [comment]
@johnbillion I'd like to get input from a couple other team members before making that change, but we can add it in the next version if that's a popular preference!

**Comment by kadamwhite** [comment]
@johnbillion I actually just ran into a couple issues recently caused by unexpected behavior with plugins which are bundled with presets. Because it is _significantly_ easier to add a plugin to a configuration than to remove one once added, I actually now intend to _remove_ another "convenience" plugin from the production preset in 0.8.0, and would prefer not to introduce other plugins to those presets — however generally useful and benign they seem — unless it is strictly necessary.

We could evaluate creating an `hm` preset generator which includes more niceties, but I think it's best to keep `development()` and `production()` as minimal as possible.

**Comment by johnbillion** [comment]
This is a good point, in that case happy to leave as an opt-in plugin.

**Pull request merged**
